# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f828db3c5fd721ff74fd38922683b8d1cb87e30eff543894f1123560cae79c36a16d2770ba0d88fe6b72d98d7054aa4684ae502ff6c3e32a0303e350f4525b

test:
  secret_key_base: d66f1be39cb758ac3fcba902201f896dac57c597308b824717a6373ae35d573765ebb992270b5acbbf2d4c96337ed792511f7c460c4afa490f2b9c5639e541a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
